In [1]:
import tensorflow as tf
print(tf.__version__)
msg = tf.constant('TensorFlow 2.0 Hello World')
tf.print(msg)

2.9.1
TensorFlow 2.0 Hello World


In [2]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Input, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam, SGD, RMSprop, Adagrad
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras import backend as K

In [3]:
def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

In [4]:
X, y = load_boston(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y)

C:\Users\fedic\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [5]:
print(X_train.shape)
print(y_train.shape)

(379, 13)
(379,)


In [6]:
print(X_test.shape)
print(y_test.shape)

(127, 13)
(127,)


In [7]:
model = Sequential([
    Dense(128, activation='relu', input_shape=(13,)),
    Dense(256, activation='relu'),
    Dense(128, activation='relu'),
    Dense(1)
])

model.compile(
    optimizer=Adam(), 
    loss='mse', 
    metrics=[RootMeanSquaredError()]
)

In [8]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
12/12 [==============================] - 1s 2ms/step - loss: 291.1481 - root_mean_squared_error: 17.0631
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 85.3879 - root_mean_squared_error: 9.2406
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 74.4856 - root_mean_squared_error: 8.6305
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 64.9552 - root_mean_squared_error: 8.0595
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 64.5057 - root_mean_squared_error: 8.0315
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 76.7862 - root_mean_squared_error: 8.7628
Epoch 7/100
12/12 [==============================] - 0s 3ms/step - loss: 78.2731 - root_mean_squared_error: 8.8472
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 62.1551 - root_mean_squared_error: 7.8839
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 56.20

12/12 [==============================] - 0s 2ms/step - loss: 19.9829 - root_mean_squared_error: 4.4702
Epoch 72/100
12/12 [==============================] - 0s 2ms/step - loss: 22.1677 - root_mean_squared_error: 4.7083
Epoch 73/100
12/12 [==============================] - 0s 2ms/step - loss: 21.2577 - root_mean_squared_error: 4.6106
Epoch 74/100
12/12 [==============================] - 0s 2ms/step - loss: 23.1656 - root_mean_squared_error: 4.8131
Epoch 75/100
12/12 [==============================] - 0s 2ms/step - loss: 25.2588 - root_mean_squared_error: 5.0258
Epoch 76/100
12/12 [==============================] - 0s 2ms/step - loss: 21.7625 - root_mean_squared_error: 4.6650
Epoch 77/100
12/12 [==============================] - 0s 2ms/step - loss: 23.8202 - root_mean_squared_error: 4.8806
Epoch 78/100
12/12 [==============================] - 0s 2ms/step - loss: 20.1541 - root_mean_squared_error: 4.4893
Epoch 79/100
12/12 [==============================] - 0s 2ms/step - loss: 19.1658 - r

In [9]:
predict_y = model.predict(X_test)
predict_y[:5]

4/4 [==============================] - 0s 2ms/step


array([[21.220531],
       [24.021233],
       [16.993698],
       [11.07815 ],
       [13.604284]], dtype=float32)

In [10]:
y_test[:5]

array([24.8, 21.7, 15.2, 13.5,  9.7])

In [11]:
rmse(y_test, predict_y).numpy()

12.667615557710132

Выше был построен пример модели для предсказания задачи регрессии.

Попробуем поменять некоторые параметры этой сети и запишем результаты работы, а после сравним их.

Все модели будут обучаться на 100 эпохах

In [12]:
# сюда будем записывать основные параметры модели
params = []

# итоговая метрика для модели на тетсовых данных
metrics = []

Для начала построим сеть с одним скрытым слоем с 256ю нейронами и функцией активации relu, первый слой будет иметь 128 нейровнов и функцию активации linear и выходной слой с одним нейроном без функции активации.

In [13]:
params.append({"layers": 1, "hiddenLayersNeurons": 256, "hiddenLayersFunc": "relu", "optimizer": "Adam"})

In [14]:
model = Sequential([
    Dense(128, activation='linear', input_shape=(13,)),
    Dense(256, activation='relu'),
    Dense(1)
])

model.compile(
    optimizer=Adam(), 
    loss='mse', 
    metrics=[RootMeanSquaredError()]
)

In [15]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
12/12 [==============================] - 0s 2ms/step - loss: 1291.9730 - root_mean_squared_error: 35.9440
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 317.6756 - root_mean_squared_error: 17.8235
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 146.9256 - root_mean_squared_error: 12.1213
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 82.9933 - root_mean_squared_error: 9.1101
Epoch 5/100
12/12 [==============================] - 0s 1ms/step - loss: 65.5039 - root_mean_squared_error: 8.0935
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 63.8666 - root_mean_squared_error: 7.9917
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 77.4082 - root_mean_squared_error: 8.7982
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 69.5210 - root_mean_squared_error: 8.3379
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 

12/12 [==============================] - 0s 2ms/step - loss: 39.2394 - root_mean_squared_error: 6.2641
Epoch 72/100
12/12 [==============================] - 0s 2ms/step - loss: 69.8607 - root_mean_squared_error: 8.3583
Epoch 73/100
12/12 [==============================] - 0s 2ms/step - loss: 91.3914 - root_mean_squared_error: 9.5599
Epoch 74/100
12/12 [==============================] - 0s 2ms/step - loss: 64.1141 - root_mean_squared_error: 8.0071
Epoch 75/100
12/12 [==============================] - 0s 2ms/step - loss: 37.2436 - root_mean_squared_error: 6.1028
Epoch 76/100
12/12 [==============================] - 0s 2ms/step - loss: 44.1845 - root_mean_squared_error: 6.6471
Epoch 77/100
12/12 [==============================] - 0s 3ms/step - loss: 43.1465 - root_mean_squared_error: 6.5686
Epoch 78/100
12/12 [==============================] - 0s 2ms/step - loss: 46.9554 - root_mean_squared_error: 6.8524
Epoch 79/100
12/12 [==============================] - 0s 2ms/step - loss: 52.7384 - r

In [16]:
y_predict = model.predict(X_test)
print(y_predict[:5])
print(y_test[:5])

4/4 [==============================] - 0s 2ms/step
[[17.744942]
 [21.857151]
 [15.796645]
 [ 5.085099]
 [ 9.727954]]
[24.8 21.7 15.2 13.5  9.7]


In [17]:
metric = rmse(y_test, y_predict).numpy()
print(metric)

11.77192442137926


In [18]:
metrics.append(metric)

Теперь поиграем с количеством скрытых слоев и запишем результаты

In [19]:
layers = [2, 3, 5, 10]

In [20]:
for layer in layers:
    params.append({"layers": layer, "hiddenLayersNeurons": 256, "hiddenLayersFunc": "relu", "optimizer": "Adam"})
    print(f"Count hidden layers: {layer}")
    
    model = Sequential(name='test_model')
    model.add( Dense( 128, activation='linear', input_shape=(13,))) 
    
    for index in range(layer):
        model.add( Dense( 256, activation='relu')) 
    
    model.add( Dense(1))

    model.compile(
        optimizer=Adam(), 
        loss='mse', 
        metrics=[RootMeanSquaredError()]
    )
    
    model.fit(X_train, y_train, epochs=100, verbose = 0)
    
    y_predict = model.predict(X_test)
    
    metric = rmse(y_test, y_predict).numpy()
    print(f"{metric=}")
    
    metrics.append(metric)

Count hidden layers: 2
4/4 [==============================] - 0s 2ms/step
metric=12.062669596245446
Count hidden layers: 3
4/4 [==============================] - 0s 3ms/step
metric=12.805922751317889
Count hidden layers: 5
4/4 [==============================] - 0s 3ms/step
metric=13.735003635058144
Count hidden layers: 10
4/4 [==============================] - 0s 4ms/step
metric=13.261596092041827


Лучше всех показала себя сеть с 2 скрытыми слоям, продолжим исследование с ней. Теперь попробуем поменять число нейронов на скрытых слоях

In [21]:
neurons = [64, 128, 384, 512]

In [22]:
for neuron in neurons:
    params.append({"layers": 2, "hiddenLayersNeurons": neuron, "hiddenLayersFunc": "relu", "optimizer": "Adam"})
    print(f"Count neurons on hidden layers: {neuron}")
    
    model = Sequential(name='test_model')
    model.add( Dense( 128, activation='linear', input_shape=(13,))) 
    
    model.add( Dense( neuron, activation='relu')) 
    model.add( Dense( neuron, activation='relu')) 
    
    model.add( Dense(1))

    model.compile(
        optimizer=Adam(), 
        loss='mse', 
        metrics=[RootMeanSquaredError()]
    )
    
    model.fit(X_train, y_train, epochs=100, verbose = 0)
    
    y_predict = model.predict(X_test)
    
    metric = rmse(y_test, y_predict).numpy()
    print(f"{metric=}")
    
    metrics.append(metric)

Count neurons on hidden layers: 64
4/4 [==============================] - 0s 2ms/step
metric=12.918452325747097
Count neurons on hidden layers: 128
4/4 [==============================] - 0s 2ms/step
metric=12.849934156055932
Count neurons on hidden layers: 384
4/4 [==============================] - 0s 2ms/step
metric=13.353689541961682
Count neurons on hidden layers: 512
4/4 [==============================] - 0s 3ms/step
metric=12.62412966268529


На данном этапе лучше всего себя показала модель с 512 нейронами. Зафиксируем этот параметр и перейдем к экспериментам с функцией активации

In [23]:
funcs = ["linear", "sigmoid", "tanh"]

In [24]:
for func in funcs:
    params.append({"layers": 2, "hiddenLayersNeurons": 512, "hiddenLayersFunc": func, "optimizer": "Adam"})
    print(f"Func on hidden layers: {func}")
    
    model = Sequential(name='test_model')
    model.add( Dense( 128, activation='linear', input_shape=(13,))) 
    
    model.add( Dense( 512, activation=func)) 
    model.add( Dense( 512, activation=func)) 
    
    model.add( Dense(1))

    model.compile(
        optimizer=Adam(), 
        loss='mse', 
        metrics=[RootMeanSquaredError()]
    )
    
    model.fit(X_train, y_train, epochs=100, verbose = 0)
    
    y_predict = model.predict(X_test)
    
    metric = rmse(y_test, y_predict).numpy()
    print(f"{metric=}")
    
    metrics.append(metric)

Func on hidden layers: linear
4/4 [==============================] - 0s 2ms/step
metric=13.98342152442655
Func on hidden layers: sigmoid
4/4 [==============================] - 0s 3ms/step
metric=11.922854903563541
Func on hidden layers: tanh
4/4 [==============================] - 0s 3ms/step
metric=11.555270103538502


Лучше всех показала себя модель с функцией активации tanh, зафиксируем этот параметр и поэксперементируем с функцией оптимизации

In [25]:
optimizers = ["SGD", "RMSprop", "Adagrad"]

In [26]:
for optimizer in optimizers:
    params.append({"layers": 2, "hiddenLayersNeurons": 512, "hiddenLayersFunc": "tanh", "optimizer": optimizer})
    print(f"Optimizer: {optimizer}")
    
    model = Sequential(name='test_model')
    model.add( Dense( 128, activation='linear', input_shape=(13,))) 
    
    model.add( Dense( 512, activation="tanh")) 
    model.add( Dense( 512, activation="tanh")) 
    
    model.add( Dense(1))

    model.compile(
        optimizer=optimizer, 
        loss='mse', 
        metrics=[RootMeanSquaredError()]
    )
    
    model.fit(X_train, y_train, epochs=100, verbose = 0)
    
    y_predict = model.predict(X_test)
    
    metric = rmse(y_test, y_predict).numpy()
    print(f"{metric=}")
    
    metrics.append(metric)

Optimizer: SGD
4/4 [==============================] - 0s 4ms/step
metric=nan
Optimizer: RMSprop
4/4 [==============================] - 0s 3ms/step
metric=11.561908638852827
Optimizer: Adagrad
4/4 [==============================] - 0s 3ms/step
metric=11.258166620940317


Теперь можем вывести все данные в одну таблицу и провести анализ

In [27]:
from IPython.display import HTML, display

In [28]:
def dataToTable(params, metrics, columns):
    hdr = ''
    
    for col in columns:
        hdr = hdr + '<th>' + col + '</th>'
    
    hdr = '<tr>' + hdr + '</tr>'

    dt = ''
    
    for index in range(len(params)):
        param = params[index]
        metric = metrics[index]
        
        dt = dt + '<tr>'
        
        dt = dt + '<td>' + str(param["layers"])+ '</td>'
        dt = dt + '<td>' + str(param["hiddenLayersNeurons"])+ '</td>'
        dt = dt + '<td>' + param["hiddenLayersFunc"]+ '</td>'
        dt = dt + '<td>' + param["optimizer"]+ '</td>'
        dt = dt + '<td>' + str(metric) + '</td>'
            
        dt = dt + '</tr>'
            
    display(HTML('<table>' + hdr + dt + '</table>'))

dataToTable(params, metrics, columns=["Количество слоев","Количествой нейронов", "Функция активации", "Функция активизации", "Метрика"])

Из таблицы можно сделать вывод что более сильное влияние на модель оказывает количество слоев и тут нельзя переборщить, наших данных не так много.

Количество нейронов в скрытых слоях не сильно влияют на модель, возможно в будующих исследованиях надо пробовать делать их разным на каждом слое.

Лучше всех себя показала функция активации **tanh**, но тут так же можно проводить экспиременты с разными функциями активации

Функцию оптимизации SGD. лучше не использовать, она не работает на этих данных. А лучше всех подходит **Adagrad**